### ISSUE TITLE
Error 127 when executing init.sh file

### ISSUE THREAD

**Issue by Royalflash5220** [xypwn/southpark-de-downloader#3]
Here a part of the output with my home directory name censored with ****

Can you help me?

patching file yt-dlc/youtube_dlc/extractor/southpark.py
>>> Building youtube-dlc
make: Entering directory '/home/****/southpark-de-downloader/yt-dlc'
mkdir -p zip
for d in youtube_dlc youtube_dlc/downloader youtube_dlc/extractor youtube_dlc/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dlc/*.py zip/youtube_dlc/*/*.py
mv zip/youtube_dlc/__main__.py zip/
cd zip ; zip -q ../youtube-dlc youtube_dlc/*.py youtube_dlc/*/*.py __main__.py
/bin/sh: 1: zip: not found
make: *** [Makefile:65: youtube-dlc] Error 127
make: Leaving directory '/home/mario/southpark-de-downloader/yt-dlc'

**Comment by xypwn** [comment]
It looks like you don't have a 'zip' executable. You should be able to install it from your package manager :)

**Comment by Royalflash5220** [comment]
i got that fixed now :) 

Now when i try to download anything, i get this error:
`~/southpark-de-downloader$ ./southpark-downloader.sh -pD -s 10 -e 6
>>> Updating episode index
>>> Going to download Season 10 Episode 6
>>> Downloading Season 10 Episode 6 (https://www.southpark.de/folgen/diujt8/south-park-mannbaerschwein-staffel-10-ep-6)
[download] Downloading playlist: Mannbärschwein
[download] Downloading video 1 of 5
[download] Merging video files
mv: cannot stat './*.mp4': No such file or directory
>>> Cleaning up temporary files`

Can you help me? Sorry for bothering you :/

**Comment by xypwn** [comment]
Hi! Apologies for the delayed response - I missed your comment earlier since the issue had already been closed. In the future, it would be great if you could open a new issue for better visibility.

I'd be happy to help you out! Since there have been a few updates recently, please go ahead and update your repository by running `git pull`. After that, try the command once more, and if you encounter any errors, please open a new issue with the error log. If everything works smoothly without any issues, feel free to comment back here. Looking forward to getting this resolved for you!
