### ISSUE TITLE
Can't download(I already downloaded yt-dlp by ur script)

### ISSUE THREAD

**Issue by csiejimmyliu** [xypwn/southpark-de-downloader#6]
Here is the error in terminal

(base) ➜  southpark-de-downloader git:(master) ./southpark-downloader.sh -s 1 -e 1
readlink: illegal option -- e
usage: readlink [-fn] [file ...]
\e[32m>>> Updating episode index\e[msed: 1: "\@^https://www.southpar ...": unexpected EOF (pending }'s)

\e[32m>>> Going to download Season 1 Episode 1\e[m
\e[32m>>> Downloading Season 1 Episode 1 (https://www.southpark.de/en/episodes/940f8z/south-park-cartman-gets-an-anal-probe-season-1-ep-1)\e[m
\e[32m>>> possible youtube-dl \e[1;31mERROR\e[m\e[m
\e[32m>>> Cleaning up temporary files\e[m
du: invalid option -- b
usage: du [-Aclnx] [-H | -L | -P] [-g | -h | -k | -m] [-a | -s | -d depth] [-B blocksize] [-I mask] [-t threshold] [file ...]

**Comment by xypwn** [comment]
Hi, your terminal output suggests that this issue exists because your versions of `readlink` and `du` don't support the options I used. To fix this, I made the script use more POSIX-compliant syntax. I only tested the new version with busybox, so you'll have to let me know if it also works on your system now. Just run git `git pull` in the cloned repo to get the latest version and let me know your results!

**Comment by csiejimmyliu** [comment]
It works! However, my region is Taiwan, and the "www.southpark.de/en" is not working in my region.
I modify some initial URL settings in https://github.com/xypwn/southpark-de-downloader/pull/7 so the EN version can be downloaded from "www.southparkstudios.com".

BTW, I'm running this script in Ubuntu 18.04.5

Thanks for your help, Southpark rules!

**Comment by xypwn** [comment]
Thanks for your response! I originally made this script for `southpark.de` (Germany) and didn't even know it could be generalized for other countries. Nice! Anyways, although I can't accept your PR, because it breaks the script for other regions, I did make my own changes that (hopefully) also work for Taiwan and many other countries.

No problem! And let me know if it works.

**Comment by xypwn** [comment]
I'll take your thumbs up as it working now and close the issue. Let me know if you have any other problems with the script and have a great day!
